algoritmo "8"
var
total,vv,vn,vb:inteiro
inicio
escreval("Digite o número total de eleitores:")
leia(total)
escreval("Digite o total de votos válidos:")
leia(vv)
escreval("Digite o total de votos nulos:")
leia(vn)
escreval("Digite o total de votos brancos:")
leia(vb)
escreval("O total de votos válidos é:",vv*100/total,"%")
escreval("O total de votos nulos é:",vn*100/total,"%")
escreval("O total de votos brancos é:",vb*100/total,"%")
fimalgoritmo
